[project]
name = "P5_Deployez_un_modele_de_Machine_Learning"
version = "0.0.1"
description = "Cette mission suit un scénario de projet professionnel. Déployer un modèle de machine learning à l’aide d’outils modernes."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.143.0",
    "ruff>=0.16.10",
]
